project:
  type: website
output-dir: docs/

website:
  title: "Why Real-World Representation in ML Datasets Matters"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: cosmo
    css: styles.css